<a href="https://colab.research.google.com/github/sreeram-gr/PythonPractice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

list_num=[1,2,3,4,5]
array_num=np.array(list_num)
print(array_num)

[1 2 3 4 5]


In [2]:
type(array_num)

numpy.ndarray

In [8]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
array_of_evens = np.arange(2,50,2)
print(array_of_evens)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [10]:
array_of_floats = np.arange(0,2,0.2)
print(array_of_floats)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [12]:
array_2D = np.array([(1,3,5),(2,4,6)])
array_2D

array([[1, 3, 5],
       [2, 4, 6]])

In [13]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
array_nd=np.arange(9).reshape(3,3)
array_nd

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
array_ones=np.ones_like(array_nd)
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])